# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task\taskMainUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_taskMain(object):
    def setupUi(self, taskMain):
        taskMain.setObjectName("taskMain")
        taskMain.resize(1061, 455)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(taskMain.sizePolicy().hasHeightForWidth())
        taskMain.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(taskMain)
        self.gridLayout.setObjectName("gridLayout")
        self.line1 = QtWidgets.QFrame(taskMain)
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 0, 1, 1, 1)
        self.line2 = QtWidgets.QFrame(taskMain)
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.gridLayout.addWidget(self.line2, 0, 3, 1, 1)
        self.plotsWidget = QtWidgets.QWidget(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotsWidget.sizePolicy().hasHeightForWidth())
        self.plotsWidget.setSizePolicy(sizePolicy)
        self.plotsWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.plotsWidget.setObjectName("plotsWidget")
        self.gridLayout.addWidget(self.plotsWidget, 0, 0, 1, 1)
        self.rightFormLayout = QtWidgets.QFormLayout()
        self.rightFormLayout.setObjectName("rightFormLayout")
        self.sessionInformationLabel = QtWidgets.QLabel(taskMain)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sessionInformationLabel.setFont(font)
        self.sessionInformationLabel.setObjectName("sessionInformationLabel")
        self.rightFormLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.sessionInformationLabel)
        self.mouseCageLabel1 = QtWidgets.QLabel(taskMain)
        self.mouseCageLabel1.setObjectName("mouseCageLabel1")
        self.rightFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mouseCageLabel1)
        self.mouseCageLabel2 = QtWidgets.QLabel(taskMain)
        self.mouseCageLabel2.setObjectName("mouseCageLabel2")
        self.rightFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mouseCageLabel2)
        self.mouseIdLabel = QtWidgets.QLabel(taskMain)
        self.mouseIdLabel.setObjectName("mouseIdLabel")
        self.rightFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mouseIdLabel)
        self.mouseIdLabel2 = QtWidgets.QLabel(taskMain)
        self.mouseIdLabel2.setObjectName("mouseIdLabel2")
        self.rightFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mouseIdLabel2)
        self.trainingPhaseLabel1 = QtWidgets.QLabel(taskMain)
        self.trainingPhaseLabel1.setObjectName("trainingPhaseLabel1")
        self.rightFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.trainingPhaseLabel1)
        self.trainingPhaseLabel2 = QtWidgets.QLabel(taskMain)
        self.trainingPhaseLabel2.setObjectName("trainingPhaseLabel2")
        self.rightFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trainingPhaseLabel2)
        self.comPortLabel1 = QtWidgets.QLabel(taskMain)
        self.comPortLabel1.setObjectName("comPortLabel1")
        self.rightFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.comPortLabel1)
        self.comPortLabel2 = QtWidgets.QLabel(taskMain)
        self.comPortLabel2.setObjectName("comPortLabel2")
        self.rightFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comPortLabel2)
        self.guiControlsLabel = QtWidgets.QLabel(taskMain)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.guiControlsLabel.setFont(font)
        self.guiControlsLabel.setObjectName("guiControlsLabel")
        self.rightFormLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.guiControlsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playButton = QtWidgets.QPushButton(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.rightFormLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.messageTextBrowser = QtWidgets.QTextBrowser(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageTextBrowser.sizePolicy().hasHeightForWidth())
        self.messageTextBrowser.setSizePolicy(sizePolicy)
        self.messageTextBrowser.setObjectName("messageTextBrowser")
        self.rightFormLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.messageTextBrowser)
        self.textBrowser = QtWidgets.QTextBrowser(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.rightFormLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.textBrowser)
        self.gridLayout.addLayout(self.rightFormLayout, 0, 4, 1, 1)
        self.leftFormLayout = QtWidgets.QFormLayout()
        self.leftFormLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.leftFormLayout.setObjectName("leftFormLayout")
        self.performanceStatisticsLabel = QtWidgets.QLabel(taskMain)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.performanceStatisticsLabel.setFont(font)
        self.performanceStatisticsLabel.setObjectName("performanceStatisticsLabel")
        self.leftFormLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.performanceStatisticsLabel)
        self.excludeGridLayout = QtWidgets.QGridLayout()
        self.excludeGridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.excludeGridLayout.setObjectName("excludeGridLayout")
        self.excludeFreeDrops = QtWidgets.QCheckBox(taskMain)
        self.excludeFreeDrops.setObjectName("excludeFreeDrops")
        self.excludeGridLayout.addWidget(self.excludeFreeDrops, 0, 1, 1, 1)
        self.excludeLabel = QtWidgets.QLabel(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excludeLabel.sizePolicy().hasHeightForWidth())
        self.excludeLabel.setSizePolicy(sizePolicy)
        self.excludeLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.excludeLabel.setObjectName("excludeLabel")
        self.excludeGridLayout.addWidget(self.excludeLabel, 0, 0, 1, 1)
        self.excludeNoLicks = QtWidgets.QCheckBox(taskMain)
        self.excludeNoLicks.setObjectName("excludeNoLicks")
        self.excludeGridLayout.addWidget(self.excludeNoLicks, 1, 1, 1, 1)
        self.leftFormLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.excludeGridLayout)
        self.toTrLabel = QtWidgets.QLabel(taskMain)
        self.toTrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.toTrLabel.setObjectName("toTrLabel")
        self.leftFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.toTrLabel)
        self.toTrStatLabel = QtWidgets.QLabel(taskMain)
        self.toTrStatLabel.setObjectName("toTrStatLabel")
        self.leftFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.toTrStatLabel)
        self.teTrLabel = QtWidgets.QLabel(taskMain)
        self.teTrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teTrLabel.setObjectName("teTrLabel")
        self.leftFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.teTrLabel)
        self.teTrStatLabel = QtWidgets.QLabel(taskMain)
        self.teTrStatLabel.setObjectName("teTrStatLabel")
        self.leftFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.teTrStatLabel)
        self.noTrLabel = QtWidgets.QLabel(taskMain)
        self.noTrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.noTrLabel.setObjectName("noTrLabel")
        self.leftFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.noTrLabel)
        self.noTrStatLabel = QtWidgets.QLabel(taskMain)
        self.noTrStatLabel.setObjectName("noTrStatLabel")
        self.leftFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.noTrStatLabel)
        self.noLiTrLabel = QtWidgets.QLabel(taskMain)
        self.noLiTrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.noLiTrLabel.setObjectName("noLiTrLabel")
        self.leftFormLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.noLiTrLabel)
        self.noLiTrStatLabel = QtWidgets.QLabel(taskMain)
        self.noLiTrStatLabel.setObjectName("noLiTrStatLabel")
        self.leftFormLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.noLiTrStatLabel)
        self.frDrTrLabel = QtWidgets.QLabel(taskMain)
        self.frDrTrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frDrTrLabel.setObjectName("frDrTrLabel")
        self.leftFormLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.frDrTrLabel)
        self.frDrTrStatLabel = QtWidgets.QLabel(taskMain)
        self.frDrTrStatLabel.setObjectName("frDrTrStatLabel")
        self.leftFormLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.frDrTrStatLabel)
        self.label = QtWidgets.QLabel(taskMain)
        self.label.setObjectName("label")
        self.leftFormLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label)
        self.toDrStatLabel = QtWidgets.QLabel(taskMain)
        self.toDrStatLabel.setObjectName("toDrStatLabel")
        self.leftFormLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.toDrStatLabel)
        self.coTrLabel = QtWidgets.QLabel(taskMain)
        self.coTrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coTrLabel.setObjectName("coTrLabel")
        self.leftFormLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.coTrLabel)
        self.coTrStatLabel = QtWidgets.QLabel(taskMain)
        self.coTrStatLabel.setObjectName("coTrStatLabel")
        self.leftFormLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.coTrStatLabel)
        self.coFrLabel = QtWidgets.QLabel(taskMain)
        self.coFrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coFrLabel.setObjectName("coFrLabel")
        self.leftFormLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.coFrLabel)
        self.coPeStatLabel = QtWidgets.QLabel(taskMain)
        self.coPeStatLabel.setObjectName("coPeStatLabel")
        self.leftFormLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.coPeStatLabel)
        self.inTrLabel = QtWidgets.QLabel(taskMain)
        self.inTrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inTrLabel.setObjectName("inTrLabel")
        self.leftFormLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.inTrLabel)
        self.inTrStatLabel = QtWidgets.QLabel(taskMain)
        self.inTrStatLabel.setObjectName("inTrStatLabel")
        self.leftFormLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.inTrStatLabel)
        self.inTrFrLabel = QtWidgets.QLabel(taskMain)
        self.inTrFrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inTrFrLabel.setObjectName("inTrFrLabel")
        self.leftFormLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.inTrFrLabel)
        self.inPeStatLabel = QtWidgets.QLabel(taskMain)
        self.inPeStatLabel.setObjectName("inPeStatLabel")
        self.leftFormLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.inPeStatLabel)
        self.biRiSiLabel = QtWidgets.QLabel(taskMain)
        self.biRiSiLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.biRiSiLabel.setObjectName("biRiSiLabel")
        self.leftFormLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.biRiSiLabel)
        self.biRiSiStatLabel = QtWidgets.QLabel(taskMain)
        self.biRiSiStatLabel.setObjectName("biRiSiStatLabel")
        self.leftFormLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.biRiSiStatLabel)
        self.biLeSiLabel = QtWidgets.QLabel(taskMain)
        self.biLeSiLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.biLeSiLabel.setObjectName("biLeSiLabel")
        self.leftFormLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.biLeSiLabel)
        self.biLeSiStatLabel = QtWidgets.QLabel(taskMain)
        self.biLeSiStatLabel.setObjectName("biLeSiStatLabel")
        self.leftFormLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.biLeSiStatLabel)
        self.plotSettingsLabel = QtWidgets.QLabel(taskMain)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plotSettingsLabel.setFont(font)
        self.plotSettingsLabel.setObjectName("plotSettingsLabel")
        self.leftFormLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.plotSettingsLabel)
        self.plotGridLayout = QtWidgets.QGridLayout()
        self.plotGridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotGridLayout.setObjectName("plotGridLayout")
        self.perfAutoScrollHorizontalLayout = QtWidgets.QHBoxLayout()
        self.perfAutoScrollHorizontalLayout.setObjectName("perfAutoScrollHorizontalLayout")
        self.trialsSpinBox = QtWidgets.QSpinBox(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialsSpinBox.sizePolicy().hasHeightForWidth())
        self.trialsSpinBox.setSizePolicy(sizePolicy)
        self.trialsSpinBox.setMaximumSize(QtCore.QSize(35, 16777215))
        self.trialsSpinBox.setMinimum(4)
        self.trialsSpinBox.setMaximum(999)
        self.trialsSpinBox.setSingleStep(2)
        self.trialsSpinBox.setProperty("value", 10)
        self.trialsSpinBox.setObjectName("trialsSpinBox")
        self.perfAutoScrollHorizontalLayout.addWidget(self.trialsSpinBox)
        self.trialsLabel = QtWidgets.QLabel(taskMain)
        self.trialsLabel.setObjectName("trialsLabel")
        self.perfAutoScrollHorizontalLayout.addWidget(self.trialsLabel)
        self.plotGridLayout.addLayout(self.perfAutoScrollHorizontalLayout, 1, 1, 1, 1)
        self.performanceCheckBox = QtWidgets.QCheckBox(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.performanceCheckBox.sizePolicy().hasHeightForWidth())
        self.performanceCheckBox.setSizePolicy(sizePolicy)
        self.performanceCheckBox.setCheckable(True)
        self.performanceCheckBox.setChecked(True)
        self.performanceCheckBox.setObjectName("performanceCheckBox")
        self.plotGridLayout.addWidget(self.performanceCheckBox, 0, 1, 1, 1)
        self.performanceLabel = QtWidgets.QLabel(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.performanceLabel.sizePolicy().hasHeightForWidth())
        self.performanceLabel.setSizePolicy(sizePolicy)
        self.performanceLabel.setObjectName("performanceLabel")
        self.plotGridLayout.addWidget(self.performanceLabel, 0, 0, 1, 1)
        self.licksAutoScrollHorizontalLayout = QtWidgets.QHBoxLayout()
        self.licksAutoScrollHorizontalLayout.setObjectName("licksAutoScrollHorizontalLayout")
        self.secDoubleSpinBox = QtWidgets.QDoubleSpinBox(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.secDoubleSpinBox.setSizePolicy(sizePolicy)
        self.secDoubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.secDoubleSpinBox.setMinimum(2.0)
        self.secDoubleSpinBox.setMaximum(3600.0)
        self.secDoubleSpinBox.setSingleStep(2.0)
        self.secDoubleSpinBox.setProperty("value", 60.0)
        self.secDoubleSpinBox.setObjectName("secDoubleSpinBox")
        self.licksAutoScrollHorizontalLayout.addWidget(self.secDoubleSpinBox)
        self.secLabel = QtWidgets.QLabel(taskMain)
        self.secLabel.setObjectName("secLabel")
        self.licksAutoScrollHorizontalLayout.addWidget(self.secLabel)
        self.plotGridLayout.addLayout(self.licksAutoScrollHorizontalLayout, 3, 1, 1, 1)
        self.realTimeCheckBox = QtWidgets.QCheckBox(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.realTimeCheckBox.sizePolicy().hasHeightForWidth())
        self.realTimeCheckBox.setSizePolicy(sizePolicy)
        self.realTimeCheckBox.setChecked(True)
        self.realTimeCheckBox.setObjectName("realTimeCheckBox")
        self.plotGridLayout.addWidget(self.realTimeCheckBox, 2, 1, 1, 1)
        self.licksLabel = QtWidgets.QLabel(taskMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.licksLabel.sizePolicy().hasHeightForWidth())
        self.licksLabel.setSizePolicy(sizePolicy)
        self.licksLabel.setObjectName("licksLabel")
        self.plotGridLayout.addWidget(self.licksLabel, 2, 0, 1, 1)
        self.leftFormLayout.setLayout(15, QtWidgets.QFormLayout.SpanningRole, self.plotGridLayout)
        self.gridLayout.addLayout(self.leftFormLayout, 0, 2, 1, 1)

        self.retranslateUi(taskMain)
        QtCore.QMetaObject.connectSlotsByName(taskMain)

    def retranslateUi(self, taskMain):
        _translate = QtCore.QCoreApplication.translate
        taskMain.setWindowTitle(_translate("taskMain", "Form"))
        self.sessionInformationLabel.setText(_translate("taskMain", "Session Information:"))
        self.mouseCageLabel1.setText(_translate("taskMain", "Mouse Cage:"))
        self.mouseCageLabel2.setText(_translate("taskMain", "n/a"))
        self.mouseIdLabel.setText(_translate("taskMain", "Mouse ID:"))
        self.mouseIdLabel2.setText(_translate("taskMain", "n/a"))
        self.trainingPhaseLabel1.setText(_translate("taskMain", "Training Phase:"))
        self.trainingPhaseLabel2.setText(_translate("taskMain", "n/a"))
        self.comPortLabel1.setText(_translate("taskMain", "COM Port:"))
        self.comPortLabel2.setText(_translate("taskMain", "n/a"))
        self.guiControlsLabel.setText(_translate("taskMain", "GUI Controls:"))
        self.playButton.setText(_translate("taskMain", "Play"))
        self.performanceStatisticsLabel.setText(_translate("taskMain", "Performance Statistics:"))
        self.excludeFreeDrops.setText(_translate("taskMain", "Free Drops"))
        self.excludeLabel.setText(_translate("taskMain", "Exclude:"))
        self.excludeNoLicks.setText(_translate("taskMain", "No Licks"))
        self.toTrLabel.setText(_translate("taskMain", "Total Trials:"))
        self.toTrStatLabel.setText(_translate("taskMain", "0"))
        self.teTrLabel.setText(_translate("taskMain", "Template Trials:"))
        self.teTrStatLabel.setText(_translate("taskMain", "0"))
        self.noTrLabel.setText(_translate("taskMain", "Nontemplate Trials:"))
        self.noTrStatLabel.setText(_translate("taskMain", "0"))
        self.noLiTrLabel.setText(_translate("taskMain", "No Lick Trials:"))
        self.noLiTrStatLabel.setText(_translate("taskMain", "0"))
        self.frDrTrLabel.setText(_translate("taskMain", "Free Drop Trials:"))
        self.frDrTrStatLabel.setText(_translate("taskMain", "0"))
        self.label.setText(_translate("taskMain", "Total Drops:"))
        self.toDrStatLabel.setText(_translate("taskMain", "0"))
        self.coTrLabel.setText(_translate("taskMain", "Correct Trials:"))
        self.coTrStatLabel.setText(_translate("taskMain", "0"))
        self.coFrLabel.setText(_translate("taskMain", "Correct Percent:"))
        self.coPeStatLabel.setText(_translate("taskMain", "n/a"))
        self.inTrLabel.setText(_translate("taskMain", "Incorrect Trials:"))
        self.inTrStatLabel.setText(_translate("taskMain", "0"))
        self.inTrFrLabel.setText(_translate("taskMain", "Incorrect Percent:"))
        self.inPeStatLabel.setText(_translate("taskMain", "n/a"))
        self.biRiSiLabel.setText(_translate("taskMain", "Bias Right Side:"))
        self.biRiSiStatLabel.setText(_translate("taskMain", "n/a"))
        self.biLeSiLabel.setText(_translate("taskMain", "Bias Left Side:"))
        self.biLeSiStatLabel.setText(_translate("taskMain", "n/a"))
        self.plotSettingsLabel.setText(_translate("taskMain", "Plot Settings:"))
        self.trialsLabel.setText(_translate("taskMain", "trials"))
        self.performanceCheckBox.setText(_translate("taskMain", "Auto Scroll"))
        self.performanceLabel.setText(_translate("taskMain", "Trials:"))
        self.secLabel.setText(_translate("taskMain", "sec"))
        self.realTimeCheckBox.setText(_translate("taskMain", "Auto Scroll"))
        self.licksLabel.setText(_translate("taskMain", "Real-Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    taskMain = QtWidgets.QWidget()
    ui = Ui_taskMain()
    ui.setupUi(taskMain)
    taskMain.show()
    sys.exit(app.exec_())
