# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mouse\mouseUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mouse(object):
    def setupUi(self, mouse):
        mouse.setObjectName("mouse")
        mouse.resize(314, 551)
        self.centralwidget = QtWidgets.QWidget(mouse)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructionLabel = QtWidgets.QLabel(self.centralwidget)
        self.instructionLabel.setWordWrap(False)
        self.instructionLabel.setObjectName("instructionLabel")
        self.verticalLayout.addWidget(self.instructionLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newMouseRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.newMouseRadioButton.setChecked(True)
        self.newMouseRadioButton.setObjectName("newMouseRadioButton")
        self.horizontalLayout.addWidget(self.newMouseRadioButton)
        self.oldMouseRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.oldMouseRadioButton.setObjectName("oldMouseRadioButton")
        self.horizontalLayout.addWidget(self.oldMouseRadioButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.cageLabel = QtWidgets.QLabel(self.centralwidget)
        self.cageLabel.setMouseTracking(False)
        self.cageLabel.setToolTipDuration(-1)
        self.cageLabel.setWhatsThis("")
        self.cageLabel.setAccessibleDescription("")
        self.cageLabel.setObjectName("cageLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cageLabel)
        self.cageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cageLineEdit.setToolTip("")
        self.cageLineEdit.setWhatsThis("")
        self.cageLineEdit.setAccessibleDescription("")
        self.cageLineEdit.setMaxLength(10)
        self.cageLineEdit.setObjectName("cageLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cageLineEdit)
        self.mouseIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.mouseIdLabel.setObjectName("mouseIdLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mouseIdLabel)
        self.mouseIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.mouseIdLineEdit.setMaxLength(3)
        self.mouseIdLineEdit.setObjectName("mouseIdLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mouseIdLineEdit)
        self.massLabel = QtWidgets.QLabel(self.centralwidget)
        self.massLabel.setObjectName("massLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.massLabel)
        self.massLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.massLineEdit.setToolTip("")
        self.massLineEdit.setMaxLength(11)
        self.massLineEdit.setObjectName("massLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.massLineEdit)
        self.birthdayLabel = QtWidgets.QLabel(self.centralwidget)
        self.birthdayLabel.setObjectName("birthdayLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.birthdayLabel)
        self.birthdayLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.birthdayLineEdit.setToolTip("")
        self.birthdayLineEdit.setMaxLength(10)
        self.birthdayLineEdit.setObjectName("birthdayLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.birthdayLineEdit)
        self.breedLabel = QtWidgets.QLabel(self.centralwidget)
        self.breedLabel.setObjectName("breedLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.breedLabel)
        self.breedLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.breedLineEdit.setToolTip("")
        self.breedLineEdit.setMaxLength(20)
        self.breedLineEdit.setObjectName("breedLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.breedLineEdit)
        self.sexLabel = QtWidgets.QLabel(self.centralwidget)
        self.sexLabel.setObjectName("sexLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sexLabel)
        self.sexLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sexLineEdit.setToolTip("")
        self.sexLineEdit.setMaxLength(1)
        self.sexLineEdit.setObjectName("sexLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sexLineEdit)
        self.miscLabel = QtWidgets.QLabel(self.centralwidget)
        self.miscLabel.setObjectName("miscLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.miscLabel)
        self.miscTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.miscTextEdit.sizePolicy().hasHeightForWidth())
        self.miscTextEdit.setSizePolicy(sizePolicy)
        self.miscTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.miscTextEdit.setObjectName("miscTextEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.miscTextEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.mouse_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.mouse_combo_box.setEnabled(False)
        self.mouse_combo_box.setObjectName("mouse_combo_box")
        self.verticalLayout.addWidget(self.mouse_combo_box)
        self.submitPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitPushButton.setObjectName("submitPushButton")
        self.verticalLayout.addWidget(self.submitPushButton)
        self.messageTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.messageTextBrowser.setObjectName("messageTextBrowser")
        self.verticalLayout.addWidget(self.messageTextBrowser)
        self.list_mice_push_button = QtWidgets.QPushButton(self.centralwidget)
        self.list_mice_push_button.setObjectName("list_mice_push_button")
        self.verticalLayout.addWidget(self.list_mice_push_button)
        self.backPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.backPushButton.setObjectName("backPushButton")
        self.verticalLayout.addWidget(self.backPushButton)
        mouse.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mouse)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 314, 21))
        self.menubar.setObjectName("menubar")
        mouse.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mouse)
        self.statusbar.setObjectName("statusbar")
        mouse.setStatusBar(self.statusbar)

        self.retranslateUi(mouse)
        QtCore.QMetaObject.connectSlotsByName(mouse)

    def retranslateUi(self, mouse):
        _translate = QtCore.QCoreApplication.translate
        mouse.setWindowTitle(_translate("mouse", "MainWindow"))
        self.instructionLabel.setText(_translate("mouse", "Enter information about mouse to upload to SQL database."))
        self.newMouseRadioButton.setText(_translate("mouse", "New Mouse Data Submission"))
        self.oldMouseRadioButton.setText(_translate("mouse", "Old Mouse Retirement"))
        self.cageLabel.setToolTip(_translate("mouse", "integers only between 0 and 2,147,483,647"))
        self.cageLabel.setText(_translate("mouse", "Cage:"))
        self.mouseIdLabel.setToolTip(_translate("mouse", "integers only between 0 and 127"))
        self.mouseIdLabel.setText(_translate("mouse", "Mouse ID:"))
        self.massLabel.setToolTip(_translate("mouse", "number of digits cannot exceed number of x\'s on either side of decimal xxxxxx.xxxx (units in grams)"))
        self.massLabel.setText(_translate("mouse", "Baseline Mass:"))
        self.birthdayLabel.setToolTip(_translate("mouse", "YYYY-MM-DD"))
        self.birthdayLabel.setText(_translate("mouse", "Birthday:"))
        self.breedLabel.setToolTip(_translate("mouse", "20 character limit"))
        self.breedLabel.setText(_translate("mouse", "Breed:"))
        self.sexLabel.setToolTip(_translate("mouse", "\'m\' or \'f\' (without apostrophes)"))
        self.sexLabel.setText(_translate("mouse", "Sex:"))
        self.miscLabel.setToolTip(_translate("mouse", "8000 character limit"))
        self.miscLabel.setText(_translate("mouse", "Miscellaneous:"))
        self.miscTextEdit.setHtml(_translate("mouse", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.submitPushButton.setText(_translate("mouse", "Submit"))
        self.messageTextBrowser.setHtml(_translate("mouse", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.list_mice_push_button.setText(_translate("mouse", "List Mice in Database"))
        self.backPushButton.setText(_translate("mouse", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mouse = QtWidgets.QMainWindow()
    ui = Ui_mouse()
    ui.setupUi(mouse)
    mouse.show()
    sys.exit(app.exec_())
