# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mouse\newMouseConfirmUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewMouseConfirm(object):
    def setupUi(self, NewMouseConfirm):
        NewMouseConfirm.setObjectName("NewMouseConfirm")
        NewMouseConfirm.setEnabled(True)
        NewMouseConfirm.resize(337, 376)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewMouseConfirm.sizePolicy().hasHeightForWidth())
        NewMouseConfirm.setSizePolicy(sizePolicy)
        NewMouseConfirm.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewMouseConfirm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.confirmationLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.confirmationLabel.setWordWrap(False)
        self.confirmationLabel.setObjectName("confirmationLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.confirmationLabel)
        self.cageLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.cageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cageLabel.setObjectName("cageLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cageLabel)
        self.cageLabel2 = QtWidgets.QLabel(NewMouseConfirm)
        self.cageLabel2.setObjectName("cageLabel2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cageLabel2)
        self.mouseIdLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.mouseIdLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mouseIdLabel.setObjectName("mouseIdLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mouseIdLabel)
        self.mouseIdLabel2 = QtWidgets.QLabel(NewMouseConfirm)
        self.mouseIdLabel2.setObjectName("mouseIdLabel2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mouseIdLabel2)
        self.weightLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.weightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weightLabel.setObjectName("weightLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.weightLabel)
        self.weightLabel2 = QtWidgets.QLabel(NewMouseConfirm)
        self.weightLabel2.setObjectName("weightLabel2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.weightLabel2)
        self.birthdayLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.birthdayLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.birthdayLabel.setObjectName("birthdayLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.birthdayLabel)
        self.birthdayLabel2 = QtWidgets.QLabel(NewMouseConfirm)
        self.birthdayLabel2.setObjectName("birthdayLabel2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.birthdayLabel2)
        self.breedLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.breedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.breedLabel.setObjectName("breedLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.breedLabel)
        self.breedLabel2 = QtWidgets.QLabel(NewMouseConfirm)
        self.breedLabel2.setObjectName("breedLabel2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.breedLabel2)
        self.sexLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.sexLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sexLabel.setObjectName("sexLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.sexLabel)
        self.sexLabel2 = QtWidgets.QLabel(NewMouseConfirm)
        self.sexLabel2.setObjectName("sexLabel2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sexLabel2)
        self.miscLabel = QtWidgets.QLabel(NewMouseConfirm)
        self.miscLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.miscLabel.setObjectName("miscLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.miscLabel)
        self.miscTextBrowser = QtWidgets.QTextBrowser(NewMouseConfirm)
        self.miscTextBrowser.setObjectName("miscTextBrowser")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.miscTextBrowser)
        self.verticalLayout.addLayout(self.formLayout)
        self.confirmation_button_box = QtWidgets.QDialogButtonBox(NewMouseConfirm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmation_button_box.sizePolicy().hasHeightForWidth())
        self.confirmation_button_box.setSizePolicy(sizePolicy)
        self.confirmation_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.confirmation_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirmation_button_box.setCenterButtons(True)
        self.confirmation_button_box.setObjectName("confirmation_button_box")
        self.verticalLayout.addWidget(self.confirmation_button_box)

        self.retranslateUi(NewMouseConfirm)
        QtCore.QMetaObject.connectSlotsByName(NewMouseConfirm)

    def retranslateUi(self, NewMouseConfirm):
        _translate = QtCore.QCoreApplication.translate
        NewMouseConfirm.setWindowTitle(_translate("NewMouseConfirm", "Confirmation"))
        self.confirmationLabel.setText(_translate("NewMouseConfirm", "The following mouse information will be uploaded to the database:"))
        self.cageLabel.setText(_translate("NewMouseConfirm", "Cage:"))
        self.cageLabel2.setText(_translate("NewMouseConfirm", "TextLabel"))
        self.mouseIdLabel.setText(_translate("NewMouseConfirm", "Mouse ID:"))
        self.mouseIdLabel2.setText(_translate("NewMouseConfirm", "TextLabel"))
        self.weightLabel.setText(_translate("NewMouseConfirm", "BaselineWeight:"))
        self.weightLabel2.setText(_translate("NewMouseConfirm", "TextLabel"))
        self.birthdayLabel.setText(_translate("NewMouseConfirm", "Birthday:"))
        self.birthdayLabel2.setText(_translate("NewMouseConfirm", "TextLabel"))
        self.breedLabel.setText(_translate("NewMouseConfirm", "Breed:"))
        self.breedLabel2.setText(_translate("NewMouseConfirm", "TextLabel"))
        self.sexLabel.setText(_translate("NewMouseConfirm", "Sex:"))
        self.sexLabel2.setText(_translate("NewMouseConfirm", "TextLabel"))
        self.miscLabel.setText(_translate("NewMouseConfirm", "Misc:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewMouseConfirm = QtWidgets.QDialog()
    ui = Ui_NewMouseConfirm()
    ui.setupUi(NewMouseConfirm)
    NewMouseConfirm.show()
    sys.exit(app.exec_())
