# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters\parametersConfirmUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_parametersConfirm(object):
    def setupUi(self, parametersConfirm):
        parametersConfirm.setObjectName("parametersConfirm")
        parametersConfirm.setEnabled(True)
        parametersConfirm.resize(254, 525)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parametersConfirm.sizePolicy().hasHeightForWidth())
        parametersConfirm.setSizePolicy(sizePolicy)
        parametersConfirm.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(parametersConfirm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parametersConfirm)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.name_label = QtWidgets.QLabel(self.widget)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lick_window_duration_label = QtWidgets.QLabel(self.widget)
        self.lick_window_duration_label.setObjectName("lick_window_duration_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lick_window_duration_label)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.tone_duration_label = QtWidgets.QLabel(self.widget)
        self.tone_duration_label.setObjectName("tone_duration_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tone_duration_label)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.between_tones_duration_label = QtWidgets.QLabel(self.widget)
        self.between_tones_duration_label.setObjectName("between_tones_duration_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.between_tones_duration_label)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.delay_duration_label = QtWidgets.QLabel(self.widget)
        self.delay_duration_label.setObjectName("delay_duration_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.delay_duration_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_22 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.min_divergence_label = QtWidgets.QLabel(self.widget)
        self.min_divergence_label.setObjectName("min_divergence_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.min_divergence_label)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.max_divergence_label = QtWidgets.QLabel(self.widget)
        self.max_divergence_label.setObjectName("max_divergence_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.max_divergence_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.punishment_light_label = QtWidgets.QLabel(self.widget)
        self.punishment_light_label.setObjectName("punishment_light_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.punishment_light_label)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.punishment_air_label = QtWidgets.QLabel(self.widget)
        self.punishment_air_label.setObjectName("punishment_air_label")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.punishment_air_label)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.drop_size_label = QtWidgets.QLabel(self.widget)
        self.drop_size_label.setObjectName("drop_size_label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.drop_size_label)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.licks_per_decision_label = QtWidgets.QLabel(self.widget)
        self.licks_per_decision_label.setObjectName("licks_per_decision_label")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.licks_per_decision_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_4.addWidget(self.line_4)
        self.formLayout.setLayout(15, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.label_27 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.songs_per_block_label = QtWidgets.QLabel(self.widget)
        self.songs_per_block_label.setObjectName("songs_per_block_label")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.songs_per_block_label)
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.alternate_block_label = QtWidgets.QLabel(self.widget)
        self.alternate_block_label.setObjectName("alternate_block_label")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.alternate_block_label)
        self.label_31 = QtWidgets.QLabel(self.widget)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.coinflip_block_label = QtWidgets.QLabel(self.widget)
        self.coinflip_block_label.setObjectName("coinflip_block_label")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.coinflip_block_label)
        self.label_33 = QtWidgets.QLabel(self.widget)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.random_encouragement_trials_label = QtWidgets.QLabel(self.widget)
        self.random_encouragement_trials_label.setObjectName("random_encouragement_trials_label")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.random_encouragement_trials_label)
        self.label_34 = QtWidgets.QLabel(self.widget)
        self.label_34.setObjectName("label_34")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.incorrect_encouragement_trials_label = QtWidgets.QLabel(self.widget)
        self.incorrect_encouragement_trials_label.setObjectName("incorrect_encouragement_trials_label")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.incorrect_encouragement_trials_label)
        self.label_37 = QtWidgets.QLabel(self.widget)
        self.label_37.setObjectName("label_37")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.template_song_label = QtWidgets.QLabel(self.widget)
        self.template_song_label.setObjectName("template_song_label")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.template_song_label)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.song_volume_label = QtWidgets.QLabel(self.widget)
        self.song_volume_label.setObjectName("song_volume_label")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.song_volume_label)
        self.verticalLayout.addWidget(self.widget)
        self.confirmation_button_box = QtWidgets.QDialogButtonBox(parametersConfirm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmation_button_box.sizePolicy().hasHeightForWidth())
        self.confirmation_button_box.setSizePolicy(sizePolicy)
        self.confirmation_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.confirmation_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.confirmation_button_box.setCenterButtons(True)
        self.confirmation_button_box.setObjectName("confirmation_button_box")
        self.verticalLayout.addWidget(self.confirmation_button_box)

        self.retranslateUi(parametersConfirm)
        QtCore.QMetaObject.connectSlotsByName(parametersConfirm)

    def retranslateUi(self, parametersConfirm):
        _translate = QtCore.QCoreApplication.translate
        parametersConfirm.setWindowTitle(_translate("parametersConfirm", "Confirmation"))
        self.label_4.setText(_translate("parametersConfirm", "Mouse Behavior Task Parameters:"))
        self.label_2.setText(_translate("parametersConfirm", "Name:"))
        self.name_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_21.setText(_translate("parametersConfirm", "Trial Structure:"))
        self.label.setText(_translate("parametersConfirm", "Lick Window Duration:"))
        self.lick_window_duration_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_15.setText(_translate("parametersConfirm", "Tone Duration:"))
        self.tone_duration_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_13.setText(_translate("parametersConfirm", "Duration Between Tones:"))
        self.between_tones_duration_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_3.setText(_translate("parametersConfirm", "Delay Duration:"))
        self.delay_duration_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_22.setText(_translate("parametersConfirm", "Nontemplate Trial Divergence Range:"))
        self.label_5.setText(_translate("parametersConfirm", "Minimum Divergence:"))
        self.min_divergence_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_7.setText(_translate("parametersConfirm", "Maximum Divergence:"))
        self.max_divergence_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_23.setText(_translate("parametersConfirm", "Positive/Negative Feedback:"))
        self.label_11.setText(_translate("parametersConfirm", "Punishment Light:"))
        self.punishment_light_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_17.setText(_translate("parametersConfirm", "Punishment Air:"))
        self.punishment_air_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_19.setText(_translate("parametersConfirm", "Drop Size:"))
        self.drop_size_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_25.setText(_translate("parametersConfirm", "Licks Per Decision:"))
        self.licks_per_decision_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_24.setText(_translate("parametersConfirm", "Training/Miscellaneous:"))
        self.label_27.setText(_translate("parametersConfirm", "Songs Per Block:"))
        self.songs_per_block_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_29.setText(_translate("parametersConfirm", "Alternate Block:"))
        self.alternate_block_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_31.setText(_translate("parametersConfirm", "Coinflip Block:"))
        self.coinflip_block_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_33.setText(_translate("parametersConfirm", "Random Encouragement:"))
        self.random_encouragement_trials_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_34.setText(_translate("parametersConfirm", "Incorrect Encouragement:"))
        self.incorrect_encouragement_trials_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_37.setText(_translate("parametersConfirm", "Template Song:"))
        self.template_song_label.setText(_translate("parametersConfirm", "TextLabel"))
        self.label_6.setText(_translate("parametersConfirm", "Song Volume"))
        self.song_volume_label.setText(_translate("parametersConfirm", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    parametersConfirm = QtWidgets.QDialog()
    ui = Ui_parametersConfirm()
    ui.setupUi(parametersConfirm)
    parametersConfirm.show()
    sys.exit(app.exec_())
