# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sql\sqlUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sql(object):
    def setupUi(self, sql):
        sql.setObjectName("sql")
        sql.resize(294, 432)
        self.centralwidget = QtWidgets.QWidget(sql)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sqlWidget = QtWidgets.QWidget(self.centralwidget)
        self.sqlWidget.setObjectName("sqlWidget")
        self.sqlFormLayout = QtWidgets.QFormLayout(self.sqlWidget)
        self.sqlFormLayout.setObjectName("sqlFormLayout")
        self.sqlInstructionLabel = QtWidgets.QLabel(self.sqlWidget)
        self.sqlInstructionLabel.setWordWrap(True)
        self.sqlInstructionLabel.setObjectName("sqlInstructionLabel")
        self.sqlFormLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.sqlInstructionLabel)
        self.serverAddressLabel = QtWidgets.QLabel(self.sqlWidget)
        self.serverAddressLabel.setObjectName("serverAddressLabel")
        self.sqlFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.serverAddressLabel)
        self.serverAddressLineEdit = QtWidgets.QLineEdit(self.sqlWidget)
        self.serverAddressLineEdit.setObjectName("serverAddressLineEdit")
        self.sqlFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serverAddressLineEdit)
        self.usernameLabel = QtWidgets.QLabel(self.sqlWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.sqlFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.sqlWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.sqlFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.sqlWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.sqlFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.sqlWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.sqlFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.sqlPushButton = QtWidgets.QPushButton(self.sqlWidget)
        self.sqlPushButton.setObjectName("sqlPushButton")
        self.sqlFormLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.sqlPushButton)
        self.verticalLayout_2.addWidget(self.sqlWidget)
        self.goWidget = QtWidgets.QWidget(self.centralwidget)
        self.goWidget.setEnabled(False)
        self.goWidget.setObjectName("goWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.goWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wwultdLabel = QtWidgets.QLabel(self.goWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wwultdLabel.sizePolicy().hasHeightForWidth())
        self.wwultdLabel.setSizePolicy(sizePolicy)
        self.wwultdLabel.setObjectName("wwultdLabel")
        self.verticalLayout.addWidget(self.wwultdLabel)
        self.mouseInfoRadioButton = QtWidgets.QRadioButton(self.goWidget)
        self.mouseInfoRadioButton.setObjectName("mouseInfoRadioButton")
        self.verticalLayout.addWidget(self.mouseInfoRadioButton)
        self.trialParametersRadioButton = QtWidgets.QRadioButton(self.goWidget)
        self.trialParametersRadioButton.setObjectName("trialParametersRadioButton")
        self.verticalLayout.addWidget(self.trialParametersRadioButton)
        self.generatePlotsRadioButton = QtWidgets.QRadioButton(self.goWidget)
        self.generatePlotsRadioButton.setEnabled(False)
        self.generatePlotsRadioButton.setObjectName("generatePlotsRadioButton")
        self.verticalLayout.addWidget(self.generatePlotsRadioButton)
        self.behaviorTaskRadioButton = QtWidgets.QRadioButton(self.goWidget)
        self.behaviorTaskRadioButton.setChecked(True)
        self.behaviorTaskRadioButton.setObjectName("behaviorTaskRadioButton")
        self.verticalLayout.addWidget(self.behaviorTaskRadioButton)
        self.goPushButton = QtWidgets.QPushButton(self.goWidget)
        self.goPushButton.setObjectName("goPushButton")
        self.verticalLayout.addWidget(self.goPushButton)
        self.verticalLayout_2.addWidget(self.goWidget)
        self.messageTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.messageTextBrowser.setObjectName("messageTextBrowser")
        self.verticalLayout_2.addWidget(self.messageTextBrowser)
        sql.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sql)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 294, 21))
        self.menubar.setObjectName("menubar")
        sql.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sql)
        self.statusbar.setObjectName("statusbar")
        sql.setStatusBar(self.statusbar)

        self.retranslateUi(sql)
        QtCore.QMetaObject.connectSlotsByName(sql)

    def retranslateUi(self, sql):
        _translate = QtCore.QCoreApplication.translate
        sql.setWindowTitle(_translate("sql", "Behavior Task Main Menu"))
        self.sqlInstructionLabel.setText(_translate("sql", "Enter information to connect to SQL database."))
        self.serverAddressLabel.setText(_translate("sql", "Server Address"))
        self.usernameLabel.setText(_translate("sql", "Username"))
        self.passwordLabel.setText(_translate("sql", "Password"))
        self.sqlPushButton.setText(_translate("sql", "Connect"))
        self.wwultdLabel.setText(_translate("sql", "What would you like to do?"))
        self.mouseInfoRadioButton.setText(_translate("sql", "Upload/Download Mouse Information"))
        self.trialParametersRadioButton.setText(_translate("sql", "Upload/Download Behavior Task Trial Parameters"))
        self.generatePlotsRadioButton.setText(_translate("sql", "Generate Stats/Plots"))
        self.behaviorTaskRadioButton.setText(_translate("sql", "Start Behavior Task"))
        self.goPushButton.setText(_translate("sql", "Go"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sql = QtWidgets.QMainWindow()
    ui = Ui_sql()
    ui.setupUi(sql)
    sql.show()
    sys.exit(app.exec_())
